development:
  sessions:
    default:
      database: ordermeal_development
      hosts:
        - localhost:27017
      options:
        max_retries: 1
        retry_interval: 0

test:
  sessions:
    default:
      database: ordermeal_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: ordermeal_production
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0